export const csv = 'lastName,firstName,question0,score\n' +
  'Viddah,Letizia,17,5\n' +
  'Ralfston,Zaria,31,3\n' +
  'Katrine,Trixi,22,7\n' +
  'Rheingold,Sean,16,7\n' +
  'Chandler,Jeanna,30,0\n' +
  'Rodmann,Deedee,4,2\n' +
  'Horan,Sara-Ann,2,3\n' +
  'Goddard,Britni,14,2\n' +
  'Cordi,Liana,14,3\n' +
  'Si,Valeda,4,2\n' +
  'Trace,Robinia,0,3\n' +
  'Bultman,Frances,17,9\n' +
  'Riordan,Esmeralda,18,10\n' +
  'Ferrell,Jacenta,4,7\n' +
  'Suanne,Glynnis,30,7\n' +
  'Kendrick,Heddie,4,2\n' +
  'Dulciana,Carly,2,6\n' +
  'Lory,Dominga,5,2\n' +
  'Eno,Wilma,5,4\n' +
  'Connelly,Elbertina,16,2\n' +
  'Berl,Brianna,31,2\n' +
  'Carri,Ricky,27,2\n' +
  'Devlen,Wilma,5,10\n' +
  'Merna,Lucille,24,4\n' +
  'Marden,Orelia,13,2\n' +
  'Jefferey,Adele,12,6\n' +
  'Pelagias,Alleen,16,7\n' +
  'Jagir,Cassondra,23,10\n' +
  'Carolin,Christian,2,5\n' +
  'Ardra,Carree,12,6\n' +
  'Alcott,Grier,4,5\n' +
  'Wilkinson,Heida,15,6\n' +
  'Presber,Petronia,25,6\n' +
  'Alfons,Andree,15,6\n' +
  'Stover,Vere,7,2\n' +
  'Joseph,Shauna,10,7\n' +
  'Sandye,Emylee,28,8\n' +
  'Zuzana,Lita,0,5\n' +
  'Niles,Chloris,30,7\n' +
  'Hertzfeld,Sybille,30,3\n' +
  'Heisel,Starla,29,10\n' +
  'Kiersten,Imojean,7,5\n' +
  'Llovera,Lexine,31,9\n' +
  'Capello,Yetty,27,9\n' +
  'Friede,Suzette,7,3\n' +
  'Grayce,Belinda,13,9\n' +
  'Roche,Philis,14,6\n' +
  'Arvo,Lory,17,7\n' +
  'Fry,Therine,24,6\n' +
  'Sekofski,Gratia,1,4';
